version: '3'
services:
  mantranet0:
    ports:
      - 8888:8888
    volumes:
      - /var/lib/samba/usershares/openmfc_data:/usr/src/app/openmfc_data
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    build: .